[package]
name = "flappy_dragon"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
my_library = { path = "./my_library" }

[workspace]
members = ["flappy_dragon_base", "my_library", "bouncy"]
